import Head from 'next/head'
import Contact from './Contact'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app by Frank Perez and Carlos Chang" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Contact />
      </main>

      <footer>
      </footer>

    </div>
  )
}
