import Head from 'next/head'
import Image from 'next/image'

import proyecto1 from '/public/img/proyecto1.jpg'
import icoelectricidad from '/public/img/icons8-signo-de-triángulo-de-energía-96.png'
import icoclima from '/public/img/clima.png'
import icojardin from '/public/img/jardin.png'
import flechaI from '/public/img/flechaIzquierda.png'
import flechaD from '/public/img/flechaDerecha.png'
import construccion from '/public/img/construccion.png'
import fondoNaranja from '/public/img/fondoNaranja.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/css/style.css" />
        <link rel="stylesheet" href="/css/all.css" />
      </Head>
      <header class="site-header inicio">
        <div class="contenedor contenido-header">
          <div class="barra">
            <a href="/">
              <img src="/img/logo.svg" alt="Logotipo de CChang" />
            </a>
            <nav class="navegacion">
              <a href="/">Inicio</a>
              <a href="nosotros.html">Nosotros</a>
              <a href="proyectos.html">Proyectos</a>
              <a href="servicios.html">Servicios</a>
              <a href="/Contact">Contacto</a>
            </nav>
          </div>
          <h1>Construimos el futuro en el presente</h1>
        </div>
      </header>
      <section class="servicios">
        <h2>Nuestros Servicios</h2>
        <div class="iconos-servicios">

          <div class="icono">
            <div class="icono-servicio">
              <Image src={construccion} width="80%" height="80%" />
            </div>
            <h3>Construcción</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla inventore
              laudantium sed delectus quae. Nihil pariatur nobis aliquid odit quidem 
              </p>
            </div>

            <div class="icono">
              <div class="icono-servicio">
                 <Image src={icoelectricidad} width="80%" height="80%" />
              </div>
                <h3>Electricidad</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla inventore
                  laudantium sed delectus quae. Nihil pariatur nobis aliquid odit quidem 
                  </p>
            </div>

            <div class="icono">
                <div class="icono-servicio">
                  <Image src={icoclima} width="80%" height="80%" />
                </div>
                <h3>Clima y Refrigeración</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla inventore
                  laudantium sed delectus quae. Nihil pariatur nobis aliquid odit quidem 
                  </p>
            </div>

            <div class="icono">
              <div class="icono-servicio">
                  <Image src={icojardin} width="80%" height="80%" />
              </div>
                <h3>Jardinería y Áreas verdes</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla inventore
                  laudantium sed delectus quae. Nihil pariatur nobis aliquid odit quidem 
                  </p>
            </div>
        </div>
    </section>
      <section class="nosotros-principal">
        <h3>Nosotros</h3>
        <div class="contenedor">
          <div class="contenido-nosotros">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
              incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
              exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
              dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
              mollit anim id est laborum.</p>
          </div>
            <div class="celdas">
              <p><span>10</span> Años de Experiencia</p>
            </div>
            <div class="celdas">
              <p><span>100+</span> Proyectos concluidos</p>
            </div>
          </div>
      </section>
      <main >
        <div class="contenedor-naranja"></div>
          <div class="ultimos-proyectos contenedor">
            <h2>Últimos Proyectos</h2>
            <div class="contenedor-proyecto">
              <button class="boton"><Image src={flechaI} width="50%" height="50%" /></button>
              <div class="comentario-proyecto">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                  labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
                  nisi ut aliquip ex ea commodo consequat.</p>
                  <p><span>Carlos Chang Ramírez</span> CEO de la Empresa</p>
              </div>
              <div class="foto-proyecto">
                <Image src={proyecto1} width="400%" height="400%" />
              </div>
              <button class="boton"><Image src={flechaD} width="50%" height="50%" /></button>
            </div>
        </div>



        {/* <div className='imagen'>
          <Image src={buildings} width="100%" height="100%" />
        </div> */}
      </main>
      <footer>
        <div class="footer contenedor">
                <nav class="navegacion">
                    <a href="nosotros.html">Nosotros</a>
                    <a href="proyectos.html">Proyectos</a>
                    <a href="servicios.html">Servicios</a>
                    <a href="contacto.html">Contacto</a>
                </nav>
                <p>Todos los Derechos Reservados &copy; </p>
            </div>
      </footer>
    </div>
  )
}
