import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/css/style.css" />
      </Head>
      <header class="site-header inicio">
        <div class="contenedor contenido-header">
          <div class="barra">
            <a href="/">
              <img src="/img/logo.svg" alt="Logotipo de CChang" />
            </a>
            <nav class="navegacion">
              <a href="/">Inicio</a>
              <a href="nosotros.html">Nosotros</a>
              <a href="proyectos.html">Proyectos</a>
              <a href="servicios.html">Servicios</a>
              <a href="contacto.html">Contacto</a>
            </nav>
          </div>
          <h1>Construimos el futuro en el presente</h1>
        </div>
      </header>
      <main >
          
      </main>

      <footer>
        <div class="footer contenedor">
                <nav class="navegacion">
                    <a href="nosotros.html">Nosotros</a>
                    <a href="proyectos.html">Proyectos</a>
                    <a href="servicios.html">Servicios</a>
                    <a href="contacto.html">Contacto</a>
                </nav>
                <p>Todos los Derechos Reservados &copy; </p>
            </div>
      </footer>
    </div>
  )
}
